name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: "3.0.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
